### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by pastawoua** [ardean/spread-the-word#1]
Hi there,

Getting an error running the demo app,
`(node:6052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: send EMSGSIZE`

Any idea what's going? Using node 8.9.0

Thanks!
(Awesome lib btw, most of the others don't work well)

**Comment by ardean** [comment]
Thank you for your feedback.

Unfortunately, I can not reproduce this problem.
I use node v8.9.4.
Does it still occur in v0.3.0?

**Comment by pastawoua** [comment]
Fixed by #2
