### ISSUE TITLE
Server.ts imports itself

### ISSUE THREAD

**Issue by amir-arad** [ardean/spread-the-word#12]
When type checking my project I'm getting the following error:

```
node_modules/spread-the-word/dist/Server.d.ts:7:10 - error TS2440: Import declaration conflicts with local declaration of 'ServerOptions'.
```
and it does seem like `Server.d.ts` is [importing itself](https://github.com/ardean/spread-the-word/blob/3182d02dadc2cd64f6029d536bde26f7cb61e6a6/dist/Server.d.ts#L7)

**Comment by ardean** [comment]
Thank you for pointing this out @amir-arad!
I removed the self import and updated dependencies.

**Comment by amir-arad** [comment]
cool. waiting for a published version!

**Comment by ardean** [comment]
> cool. waiting for a published version!

Should be published already.
