### ISSUE TITLE
Cannot listen to simple service?

### ISSUE THREAD

**Issue by jedahan** [ardean/spread-the-word#4]
In two different node processes, i run:

```js
const stw = require('spread-the-word').default
stw.on('up', console.dir)
stw.listen({type: 'osc', protocol: 'udp', subtypes: ['livingroom']})
  .then(listener => {
    console.dir(listener)
    console.log('listening')
  })
```

```js
const stw = require('spread-the-word').default
stw.spread({type: 'osc', protocol: 'udp', subtypes: ['livingroom'], name: 'lol', hostname: 'talon.local', port: 12345})
  .then(spreader => {
    console.dir(spreader)
    console.log('spread')
  })
```

I dont get any output from the listener.

If I run this in the same process, then it works. What am I missing?

**Comment by jedahan** [comment]
As a test, I tried using [nbonjour](https://github.com/taoyuan/nbonjour) like so, and it worked:

```js
const nbonjour = require('nbonjour').create()
nbonjour.publish({type: 'osc', protocol: 'udp', subtypes: ['livingroom'], name: 'somename', port: 54321})
```

```js
const nbonjour = require('nbonjour').create()
nbonjour.find({type: 'osc', protocol: 'udp', subtypes: ['livingroom']}, console.dir)
```

**Comment by ardean** [comment]
Hello @jedahan ,
The library checks the referrer ip if it's your own and ignores your own requests.
But that was not really necessary.
In [v0.5.0](https://github.com/ardean/spread-the-word/releases/tag/v0.5.0), this behavior has been adjusted so your example should work now.

**Comment by jedahan** [comment]
Test scripts work, thanks for the quick response

**Comment by OmgImAlexis** [comment]
@ardean any chance this could be added back as an option?

**Comment by ardean** [comment]
> @ardean any chance this could be added back as an option?

@OmgImAlexis Yes, I think that is a good idea.
